name: Hello World Workflow
on:
  push:
    branshes:
      -main

jobs: 
  say hello: 
    runs-on: ubuntu-latest

 steps:
 - name: Print Hello World
   run: echo "Hello World!"
  
name: Use Secrets in Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print a Secret
      env:
        API_KEY: ${{ secrets.API_Key }}
      run: |
        echo "The API key is: $API_Key"
